# Generated by Django 4.2.16 on 2024-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='faq',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faq_images/'),
        ),
        migrations.AddField(
            model_name='faq',
            name='image_custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
